import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Dooit",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${poppins.className} h-full antialiased`}>
      <head>
        <link
          href="https://cdn.boxicons.com/3.0.8/fonts/basic/boxicons.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.boxicons.com/3.0.8/fonts/filled/boxicons-filled.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.boxicons.com/3.0.8/fonts/brands/boxicons-brands.min.css"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-full flex flex-col  ">{children}</body>
    </html>
  );
}
